name: CI

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: windows-2025
    strategy:
      matrix:
        shell: [pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          path: 'my_bucket'
      - name: Checkout Scoop
        uses: actions/checkout@v6
        with:
          repository: ScoopInstaller/Scoop
          path: 'scoop_core'
      - name: Install and cache test dependencies
        uses: Knightly1/psmodulecache@9ac0563324860dd8b9c27e9c4f32e9b5970c579d
        with:
          modules-to-cache: BuildHelpers, Pester
          shell: ${{ matrix.shell }}
      - name: Run tests
        run: |
          $env:SCOOP_HOME="$(Convert-Path '.\scoop_core')"
          .\my_bucket\bin\test.ps1
